# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version:
         - "12.16.3" # Used in Mapeo Mobile (via nodejs-mobile@0.3.1 and nodejs-mobile-react-native@0.6.1). Also in electron@10
         # "12.19.0" Currently fails - used in current version of nodejs-mobile@0.3.2 (nodejs-mobile-react-native@0.6.2)
         - "12.18.3" # Used in current electron@11
         # "14.x" Was hanging, not used in production
         - "18.17.1" # Used in nodejs-mobile-react-native@18.17.1

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
